---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```


```{r}
datazones <- read_csv("data/raw_data/scotland_datazones_2011.csv")

la_datazones <- datazones %>% 
  select(area_code = LA_Code, area_name = LA_Name) %>% 
  unique()

hb_datazones <- datazones %>% 
  select(area_code = HB_Code, area_name = HB_Name) %>% 
  unique()

datazone_lookup <- bind_rows(list("Local Authority" = la_datazones,
                                  "Health Board" = hb_datazones),
                             .id = "area_type")
```

```{r}
reconvictions <- read_csv("data/raw_data/crime_and_justice/reconvictions.csv")
```

```{r}
col_1 <- names(reconvictions)[1]
eval(col_1) == "FeatureCode"

expression <- enquo(col_1 = "area_code")


reconvictions %>% 
  janitor::clean_names() %>% 
  inner_join(datazone_lookup, by = c(!!expression)
```

```{r}
names(reconvictions)[1]
```


```{r}
join_by_quosure <- function(data, right_index = FeatureCode, left_index = area_code){
  require(dplyr)

  left_index <- enquo(left_index)
  right_index <- enquo(right_index)

  by = set_names(quo_name(left_index), quo_name(right_index))

  inner_join(data, 
            datazone_lookup,
            by = by)
}
```

```{r}
join_by_quosure(reconvictions)
```

