library(tidyverse)
library(opendatascot)

source("scripts/helper_functions.R")

# ----- Dataset Lookup -----
datasets <- read_csv("data/clean_data/ods_dataset_lookup.csv")

update_lookup <- function(URI_name) {
  datasets %>%
    mutate(in_app = ifelse(URI == URI_name, TRUE, in_app))
}

# ----- Datazones -----
datazones <- read_csv("data/raw_data/scotland_datazones_2011.csv")

la_datazones <- datazones %>% 
  select(area_code = LA_Code, area_name = LA_Name) %>% 
  unique()

hb_datazones <- datazones %>% 
  select(area_code = HB_Code, area_name = HB_Name) %>% 
  unique()

datazone_lookup <- bind_rows(list("Local Authority" = la_datazones,
                                  "Health Board" = hb_datazones),
                             .id = "area_type")

datazone_lookup %>% 
  write_csv("data/clean_data/datazone_lookup.csv")


# ----- Population Estimates -----

population_data_f <- read_csv("data/raw_data/population/population-estimates-f.csv",
                              skip = 8)
population_data_m <- read_csv("data/raw_data/population/population-estimates-m.csv",
                              skip = 8)

elongate_pop_df <- function(pop_df) {
  pop_df %>%
    rename(area_code = 1, reference_area = 2) %>% 
    mutate(area_code = str_extract(area_code, "S[0-9]+$")) %>% 
    filter(str_detect(area_code, "^S12|^S08")) %>% 
    pivot_longer(-c(1,2), names_to = "year", values_to = "value")
}

pop_data <- bind_rows(list("Male" = elongate_pop_df(population_data_m),
                           "Female" = elongate_pop_df(population_data_f)),
                      .id = "sex")

add_area_type_col<-function(df) {
  df %>% 
    mutate(area_type = case_when(
      str_detect(area_code, "^S12+") ~ "Local Authority",
      str_detect(area_code, "^S08+") ~ "Health Board"))
}

pop_data <- add_area_type_col(pop_data) %>% 
  select(area_code, reference_area, area_type, year, sex, value)

# add total pop for each area, each year
pop_data_all <- pop_data %>%
  group_by(area_code, year) %>% 
  summarise(area_code, reference_area, area_type, year,
            sex = "All", value = sum(value))

pop_data <- pop_data %>% 
  bind_rows(pop_data_all) %>% 
  # remove duplicate rows generated by the sum
  unique()

  # add units column
pop_data <- pop_data %>% 
  mutate(units = "Persons")

 # write clean data
pop_data %>% 
  write_csv("data/clean_data/population/population_estimates.csv")


# ----- Healthy Life Expectancy ------

# read in data for male and female HLE from separate files - raw data is large
male_hle_data <- read_csv("data/raw_data/population/male-healthy-life-expectancy.csv",
                          skip = 10)
female_hle_data <- read_csv("data/raw_data/population/female-healthy-life-expectancy.csv",
                            skip = 10)

# convert reference periods to long format, apply same pivot to both dfs
pivot_hle_long <- function(hle_df, df_sex) {
  long_df <- hle_df %>% 
    pivot_longer(-c(1,2), names_to = "ref_period",
                 values_to = "value") %>% 
    janitor::clean_names() %>% 
    mutate(area_code = str_extract(
      http_purl_org_linked_data_sdmx_2009_dimension_number_ref_area,
      "S[0-9]+$")) %>% 
    select(-1) %>% 
    # filter for only Health Boards at this time
    filter(!str_detect(area_code, "^S9")) %>% 
    # add sex reference column
    mutate(sex = df_sex)
}

tidy_male_hle <- pivot_hle_long(male_hle_data, "Male")
tidy_female_hle <- pivot_hle_long(female_hle_data, "Female")

# combine dfs
hle_data <- tidy_male_hle %>% 
  bind_rows(tidy_female_hle)

hle_data <- add_area_type_col(hle_data)

# generate standard output column form
hle_data <- hle_data %>% 
  select(area_code,
         reference_area,
         area_type,
         reference_period = ref_period,
         sex,
         value
         ) %>% 
  mutate(units = "Years")

# write data to clean csv
hle_data %>% 
  write_csv("data/clean_data/population/healthy_life_expectancy.csv")

# update dataset_lookup
updated_lookup <- update_lookup(URI_name = "healthy-life-expectancy")

# ----- Council House Sales -----

council_house_data <- read_csv("data/raw_data/housing/council_house_sales.csv") %>% 
  janitor::clean_names()

# units = dwellings
council_houses_better_vars <- council_house_data %>% 
  select(-c(measurement, units), area_code = feature_code, year = date_code) %>%
  # retain only health boards (S08) and local authority (S12) codes
  filter(str_detect(area_code, "^S08|^S12")) %>% 
  mutate(year = as.integer(year),
         value = as.integer(value)) %>% 
  left_join(datazone_lookup, by = c("area_code" = "area_code")) %>% 
  select(area_code,
         reference_area = area_name,
         area_type,
         year,
         dwelling_type,
         value) %>% 
  mutate(units = "Dwellings")

council_houses_better_vars %>% 
  write_csv("data/clean_data/housing/council_house_sales.csv")

updated_lookup <- update_lookup(URI_name = "council-house-sales")

# ----- Adults with low or no qualifications ----

# data comes from package: opendatascot
# geographic areas can be got only one at a time. get each then bind
adults_with_low_no_qualifications <- ods_dataset(
  "adults-16-64-years-with-low-or-no-qualifications",geography = "la"
  ) %>% 
  bind_rows(ods_dataset("adults-16-64-years-with-low-or-no-qualifications",
                        geography = "hb"))

# join with datazone lookup and clean up format for final view
adults_with_low_no_qualifications_clean <- adults_with_low_no_qualifications %>% 
  janitor::clean_names() %>% 
  mutate_if(is.character, str_to_title) %>%
  mutate(age = factor(age,
                      levels = c("16-64", "16-24", "25-34",
                                 "35-49", "50-64"))) %>% 
  rename(area_code = ref_area,
         year = ref_period) %>% 
  left_join(datazone_lookup, by = c("area_code" = "area_code")) %>% 
  select(area_code,
         reference_area = area_name,
         area_type,
         year,
         gender,
         age,
         measure_type,
         value) %>% 
  mutate(units = case_when(
    measure_type == "Count" ~ "Persons",
    measure_type == "Ratio" ~ "%%"
  ))

# write to fresh csv
adults_with_low_no_qualifications_clean %>% 
  write_csv("data/clean_data/labour_force/low_no_qualifications.csv")

updated_lookup <- update_lookup(
  URI_name = "adults-16-64-years-with-low-or-no-qualifications"
  )

# ----- Alcohol related discharges -----

# 1. get data
alcohol_related_discharge_data <- ods_dataset("alcohol-related-discharge",
                                              geography = "la") %>% 
  bind_rows(ods_dataset("alcohol-related-discharge",
                        geography = "hb"))

# 2. clean data
alcohol_related_discharge_data_clean <- alcohol_related_discharge_data %>% 
  janitor::clean_names() %>%
  rename(area_code = ref_area) %>% 
  mutate_if(is.character, str_to_title) %>%
  mutate(measure_type = ifelse(
    measure_type == "Ratio", "EASR", measure_type
    )) %>%
  left_join(datazone_lookup, by = c("area_code" = "area_code")) %>% 
  select(area_code,
         reference_area = area_name,
         area_type,
         ref_period,
         measure_type,
         value) %>% 
  mutate(units = case_when(
    measure_type == "Count" ~ "Persons",
    # rate is dimensionless
    measure_type == "EASR" ~ ""
  )) %>% 
  mutate(value = as.integer(value))

# 3. write data
alcohol_related_discharge_data_clean %>% 
  write_csv("data/clean_data/health/alcohol_related_discharge.csv")

# 4. update dataset lookup
updated_lookup <- update_lookup(URI_name = "alcohol-related-discharge")



# ----- Alcohol Related Hospital Statistics -----

arhs_data <- read_csv("data/raw_data/health/alcohol-related-hospital-stats.csv")

arhs_data_clean <- arhs_data %>%
  janitor::clean_names() %>% 
  rename(area_code = feature_code,
         reference_period = date_code) %>% 
  inner_join(datazone_lookup, by = c("area_code" = "area_code")) %>% 
  select(area_code,
         reference_area = area_name,
         area_type,
         reference_period,
         alcohol_condition,
         measure_type = measurement,
         value,
         units)

arhs_data_clean %>% 
  write_csv("data/clean_data/health/alcohol_related_hospital_stats.csv")

updated_lookup <- update_lookup(
  URI_name = "alcohol-related-hospital-statistics"
  )


# ----- Travel to Work and Other Journeys -----
travel_to_work <- read_csv("data/raw_data/transport/travel_to_work.csv")

travel_to_work_clean <- travel_to_work %>% 
  janitor::clean_names() %>% 
  left_join(datazone_lookup, by = c("feature_code" = "area_code")) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         indicator = indicator_travel_to_work,
         value,
         units)

travel_to_work_clean %>% 
  write_csv("data/clean_data/transport/travel_to_work.csv")

updated_lookup <- update_lookup(URI_name = "travel-to-work-other")

# ----- MMR immunisation -----
mmr_data <- read_csv("data/raw_data/health/mmr.csv")

mmr_clean <- mmr_data %>% 
  janitor::clean_names() %>% 
  filter(str_detect(feature_code, "^S08|^S12")) %>% 
  left_join(datazone_lookup, by = c("feature_code" = "area_code")) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         vaccination_uptake,
         measure_type = measurement,
         value,
         units)

mmr_clean %>% 
  write_csv("data/clean_data/health/mmr.csv")

updated_lookup <- update_lookup(URI_name = "measles-mumps-rubella")


# ----- Road Casualties ----- 

road_casualties <- read_csv("data/raw_data/transport/road_casualties.csv")

road_casualties_clean <- road_casualties %>% 
  janitor::clean_names() %>% 
  filter(str_detect(feature_code, "^S08|^S12")) %>% 
  left_join(datazone_lookup, by = c("feature_code" = "area_code")) %>%
  mutate(age = factor(age, levels = c("0-19 years", "20-39 years",
                                      "40-59 years", "60 years and over"))) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         age,
         gender,
         outcome,
         measure_type = measurement,
         value,
         units)
road_casualties_clean %>% 
  write_csv("data/clean_data/transport/road_casualties.csv")

updated_lookup <- update_lookup(URI_name = "road-safety")

# ----- Gender Pay Gap -----

g_pay_gap_data <- read_csv("data/raw_data/labour_force/gender_pay_gap.csv")

g_pay_data_clean <- g_pay_gap_data %>% 
  janitor::clean_names() %>% 
  inner_join(datazone_lookup, by = c("feature_code" = "area_code")) %>% 
  mutate(units = "%%") %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         working_pattern,
         value,
         units)

g_pay_data_clean %>% 
  write_csv("data/clean_data/labour_force/gender_pay_gap.csv")

updated_lookup <- update_lookup(URI_name = "earnings-paygap")

# ----- Cancer Registrations - Annual -----

cancer_regs_annual <- read_csv(
  "data/raw_data/health/cancer_registrations_annual.csv"
  )

cancer_regs_annual_clean <- cancer_regs_annual %>% 
  janitor::clean_names() %>% 
  inner_join(datazone_lookup, by = c("feature_code" = "area_code")) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         gender,
         cancer_type,
         value,
         units)

cancer_regs_annual_clean %>% 
  write_csv("data/clean_data/health/cancer_regs_annual.csv")

updated_lookup <- update_lookup(URI_name = "cancer-registrations---annual-data")

# ----- Not in Employment, Education or Training -----

neet_data <- read_csv("data/raw_data/labour_force/neet.csv")

neet_data_clean <- neet_data %>% 
  janitor::clean_names() %>% 
  inner_join(datazone_lookup, by = c("feature_code" = "area_code")) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         measure_type = measurement,
         value,
         units)

neet_data_clean %>% 
  write_csv("data/clean_data/labour_force/neet.csv")

updated_lookup <- update_lookup(URI_name = "neet")

# ---- Municipal Waste -----

municipal_waste <- read_csv("data/raw_data/environment/municipal_waste.csv")

municipal_waste_clean <- municipal_waste %>% 
  janitor::clean_names() %>% 
  inner_join(datazone_lookup, by = c("feature_code" = "area_code")) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         reference_period = date_code,
         indicator = indicator_municipal_waste,
         value,
         units)
municipal_waste_clean %>% 
  write_csv("data/clean_data/environment/municipal_waste.csv")

updated_lookup <- update_lookup(URI_name = "municipal-waste")

# ----- Earnings ----- 

earnings <- read_csv("data/raw_data/economic_activity/earnings.csv")

earnings_clean <- earnings %>% 
  janitor::clean_names() %>% 
  inner_join(datazone_lookup, by = c("feature_code" = "area_code")) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         gender,
         working_pattern,
         population_group,
         measure_type = measurement,
         value,
         units)

earnings_clean %>% 
  write_csv("data/clean_data/economic_activity/earnings.csv")

updated_lookup <- update_lookup(URI_name = "earnings")


# ----- Road Transport Expenditure ----- 

road_transport_expenditure <- read_csv(
  "data/raw_data/transport/road_transport_expenditure.csv"
  )

rte_clean <- road_transport_expenditure %>% 
  janitor::clean_names() %>% 
  inner_join(datazone_lookup, by = c("feature_code" = "area_code")) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         value,
         units)

rte_clean %>% 
  write_csv("data/clean_data/transport/road_transport_expenditure.csv")

updated_lookup <- update_lookup(URI_name = "road-transport-expenditure")

# ----- GP list size ----- 

gp_list_sizes <- read_csv("data/raw_data/health/gp_list_size.csv")

gp_list_sizes_clean <- gp_list_sizes %>% 
  janitor::clean_names() %>% 
  inner_join(datazone_lookup, by = c("feature_code" = "area_code")) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         value,
         units)

gp_list_sizes_clean %>% 
  write_csv("data/clean_data/health/gp_list_sizes.csv")

updated_lookup <- update_lookup(URI_name = "general-practice-list-size")

# ----- Energy Consumption ----- 

energy_consumption <- read_csv(
  "data/raw_data/business_enterprise_and_energy/energy_consumption.csv"
  )

energy_consumption_clean <- energy_consumption %>% 
  janitor::clean_names() %>% 
  inner_join(datazone_lookup, by = c("feature_code" = "area_code")) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         sector = energy_consuming_sector,
         energy_type,
         value,
         units)

energy_consumption_clean %>% 
  write_csv(
    "data/clean_data/business_enterprise_and_energy/energy_consumption.csv"
    )

updated_lookup <- update_lookup(URI_name = "energy-consumption")


# ----- Crimes and Offences -----

crimes_and_offences <- read_csv(
  "data/raw_data/crime_and_justice/recorded_crimes.csv"
  )

crimes_and_offences_clean <- crimes_and_offences %>% 
  janitor::clean_names() %>% 
  inner_join(datazone_lookup, by = c("feature_code" = "area_code")) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         date_code,
         crime_or_offence,
         measure_type = measurement,
         value,
         units)

crimes_and_offences_clean %>% 
  write_csv("data/clean_data/crime_and_justice/recorded_crimes.csv")

updated_lookup <- update_lookup(URI_name = "recorded-crime")

# ----- Derelict Land -----

derelict_land <- read_csv(
  "data/raw_data/community_wellbeing_and_soc_env/derelict_and_urban_vacant_land.csv"
  )

derelict_land_clean <- derelict_land %>% 
  janitor::clean_names() %>% 
  inner_join(datazone_lookup, by = c("feature_code" = "area_code")) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         area,
         value,
         units)

derelict_land_clean %>% 
  write_csv(
    "data/clean_data/community_wellbeing_and_soc_env/derelict_and_urban_vacant_land.csv"
    )

updated_lookup <- update_lookup(URI_name = "vacant-derelict-land")


# ----- reconvictions -----

reconvictions <- read_csv("data/raw_data/crime_and_justice/reconvictions.csv")

reconvictions_clean <- reconvictions %>% 
  janitor::clean_names() %>% 
  auto_join_dz_lookup(right_index = feature_code) %>% 
  mutate(age = factor(age, levels = c("All", "Under 21 years", "21-25 years",
                                      "26-30 years", "31-40 years",
                                      "Over 40 years"))) %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         date_code,
         gender,
         age,
         measure_type = measurement,
         value,
         units)

reconvictions_clean %>% 
  write_csv("data/clean_data/crime_and_justice/reconvictions.csv")

updated_lookup <- update_lookup(URI_name = "reconvictions")

# ---- HMO licenses -----

# 1. read raw data
hmo_licenses <- read_csv("data/raw_data/housing/hmo_licences.csv")

# 2. join datazone lookup and select desired columns
hmo_licenses_clean <- auto_join_dz_lookup(data = hmo_licenses) %>% 
  janitor::clean_names() %>% 
  # only one type of measurement - can be dropped from exploratory vars
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         value,
         units)
# 3. write clean (app-ready data)
hmo_licenses_clean %>% 
  write_csv("data/clean_data/housing/hmo_licences.csv")

# 4. update dataset-lookup

updated_lookup <- update_lookup(URI_name = "hmo-licences")

# ---- average household size -----

# 1. read raw data
avg_household_size <- read_csv(
  "data/raw_data//housing/average_household_size.csv"
  )

# 2. join datazone lookup and select desired columns
avg_household_size_clean <- avg_household_size %>% 
  auto_join_dz_lookup() %>% 
  janitor::clean_names() %>%
  # only one type of measurement - can remove measurement col
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         value,
         units)

# 3. write clean (app-ready data)
avg_household_size_clean %>% 
  write_csv("data/clean_data/housing/average_household_size.csv")

# 4. update dataset lookup

updated_lookup <- update_lookup(URI_name = "average_household_size")

# ----- Business Demography - births + deaths -----

# 1. read raw data
business_births_deaths <- read_csv(
  "data/raw_data/business_enterprise_and_energy/business-demography---births-and-deaths.csv"
  )

# 2. join datazone lookup and select desired columns, changing names to standard
# practice
business_births_deaths_clean <- business_births_deaths %>% 
  auto_join_dz_lookup() %>% 
  janitor::clean_names() %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         year = date_code,
         business_demography,
         measure_type = measurement,
         value,
         units)

# 3. write app-ready data
business_births_deaths_clean %>% 
  write_csv(
    "data/clean_data/business_enterprise_and_energy/business_demo_births_deaths.csv"
    )

# 4. update dataset lookup
updated_lookup <- update_lookup(
  URI_name = "business-demography---births-and-deaths"
  )

# ----- Children and Families with limited resources -----

# 1. read raw data
limited_resources <- read_csv(
  "data/raw_data/sg_children_and_young_people/children_and_families_with_limited_resources.csv"
)

# 2. join datazone lookup, reduce data to only one measure_type, change col names
# and select required columns
limited_resources_reduced <- limited_resources %>% 
  auto_join_dz_lookup() %>% 
  janitor::clean_names() %>%
  # TODO - create alternative way to deal with confidence intervals
  filter(measurement == "Percent") %>% 
  select(area_code = feature_code,
         reference_area = area_name,
         area_type,
         date_code,
         housing_costs,
         value,
         units)

# 3. write data
limited_resources_reduced %>% 
  write_csv("data/clean_data/sg_children_and_young_people/children_and_families_with_limited_resources.csv")

# 4. update dataset lookup
updated_lookup <- update_lookup(
  URI_name = "children-in-families-with-limited-resources	"
  )



# ----- Write Dataset Lookup (must be last) ------

# update dataset lookup csv
updated_lookup %>% 
  write_csv("data/clean_data/ods_dataset_lookup.csv")