library(tidyverse)

# ----- Datazones -----
datazones <- read_csv("data/raw_data/scotland_datazones_2011.csv")

la_datazones <- datazones %>% 
  select(area_code = LA_Code, area_name = LA_Name) %>% 
  unique()

hb_datazones <- datazones %>% 
  select(area_code = HB_Code, area_name = HB_Name) %>% 
  unique()

datazone_lookup <- bind_rows(list("local authority" = la_datazones,
                                  "health board" = hb_datazones),
                             .id = "area_type")

datazone_lookup %>% 
  write_csv("data/clean_data/datazone_lookup.csv")


# ----- Population Estimates -----

population_data_f <- read_csv("data/raw_data/population-estimates-f.csv",
                              skip = 8)
population_data_m <- read_csv("data/raw_data/population-estimates-m.csv",
                              skip = 8)

elongate_pop_df <- function(pop_df) {
  pop_df %>%
    rename(area_code = 1, reference_area = 2) %>% 
    mutate(area_code = str_extract(area_code, "S[0-9]+$")) %>% 
    filter(str_detect(area_code, "^S12|^S08")) %>% 
    pivot_longer(-c(1,2), names_to = "year", values_to = "value")
}

pop_data <- bind_rows(list("Male" = elongate_pop_df(population_data_m),
                           "Female" = elongate_pop_df(population_data_f)),
                      .id = "sex")
  

add_area_type_col<-function(df) {
  df %>% 
    mutate(area_type = case_when(
      str_detect(area_code, "^S12+") ~ "local authority",
      str_detect(area_code, "^S08+") ~ "health board"))
}

pop_data <- add_area_type_col(pop_data) %>% 
  select(area_code, reference_area, area_type, year, sex, value)

# add total pop for each area, each year
pop_data_all <- pop_data %>%
  group_by(area_code, year) %>% 
  summarise(area_code, reference_area, area_type, year,
            sex = "All", value = sum(value))

pop_data <- pop_data %>% 
  bind_rows(pop_data_all) %>% 
  # remove duplicate rows generated by the sum
  unique()

pop_data %>% 
  write_csv("data/clean_data/population_estimates.csv")


# ----- Healthy Life Expectancy ------

# read in data for male and female HLE from separate files
male_hle_data <- read_csv("data/raw_data/male-healthy-life-expectancy.csv",
                          skip = 10)
female_hle_data <- read_csv("data/raw_data/female-healthy-life-expectancy.csv",
                            skip = 10)

# convert reference periods to long format, apply same pivot to both dfs
pivot_hle_long <- function(hle_df, df_sex) {
  long_df <- hle_df %>% 
    pivot_longer(-c(1,2), names_to = "ref_period",
                 values_to = "value") %>% 
    janitor::clean_names() %>% 
    mutate(area_code = str_extract(
      http_purl_org_linked_data_sdmx_2009_dimension_number_ref_area,
      "S[0-9]+$")) %>% 
    select(-1) %>% 
    # filter for only Health Boards at this time
    filter(!str_detect(area_code, "^S9")) %>% 
    # add sex reference column
    mutate(sex = df_sex)
}

tidy_male_hle <- pivot_hle_long(male_hle_data, "Male")
tidy_female_hle <- pivot_hle_long(female_hle_data, "Female")

# combine dfs
hle_data <- tidy_male_hle %>% 
  bind_rows(tidy_female_hle)

hle_data <- add_area_type_col(hle_data)

# generate standard output column form
hle_data <- hle_data %>% 
  select(area_code,
         reference_area,
         area_type,
         reference_period = ref_period,
         sex,
         value
         )

# write data to clean csv
hle_data %>% 
  write_csv("../data/clean_data/healthy_life_expectancy.csv")

# ----- Council House Sales -----

council_house_data <- read_csv("data/raw_data/council_house_sales.csv") %>% 
  janitor::clean_names()

# units = dwellings
council_houses_better_vars <- council_house_data %>% 
  select(-c(measurement, units), area_code = feature_code, year = date_code) %>%
  # retain only health boards (S08) and local authority (S12) codes
  filter(str_detect(area_code, "^S08|^S12")) %>% 
  mutate(year = as.integer(year),
         value = as.integer(value)) %>% 
  left_join(datazone_lookup, by = c("area_code" = "area_code")) %>% 
  select(area_code,
         reference_area = area_name,
         area_type,
         year,
         dwelling_type,
         value)

council_houses_better_vars %>% 
  write_csv("data/clean_data/council_house_sales.csv")



  
