library(tidyverse)
library(opendatascot)

# ----- Dataset Lookup -----
datasets <- read_csv("data/clean_data/ods_dataset_lookup.csv")

update_lookup <- function(URI_name) {
  datasets %>%
    mutate(in_app = ifelse(URI == URI_name, TRUE, in_app))
}

# ----- Datazones -----
datazones <- read_csv("data/raw_data/scotland_datazones_2011.csv")

la_datazones <- datazones %>% 
  select(area_code = LA_Code, area_name = LA_Name) %>% 
  unique()

hb_datazones <- datazones %>% 
  select(area_code = HB_Code, area_name = HB_Name) %>% 
  unique()

datazone_lookup <- bind_rows(list("local authority" = la_datazones,
                                  "health board" = hb_datazones),
                             .id = "area_type")

datazone_lookup %>% 
  write_csv("data/clean_data/datazone_lookup.csv")


# ----- Population Estimates -----

population_data_f <- read_csv("data/raw_data/population-estimates-f.csv",
                              skip = 8)
population_data_m <- read_csv("data/raw_data/population-estimates-m.csv",
                              skip = 8)

elongate_pop_df <- function(pop_df) {
  pop_df %>%
    rename(area_code = 1, reference_area = 2) %>% 
    mutate(area_code = str_extract(area_code, "S[0-9]+$")) %>% 
    filter(str_detect(area_code, "^S12|^S08")) %>% 
    pivot_longer(-c(1,2), names_to = "year", values_to = "value")
}

pop_data <- bind_rows(list("Male" = elongate_pop_df(population_data_m),
                           "Female" = elongate_pop_df(population_data_f)),
                      .id = "sex")

add_area_type_col<-function(df) {
  df %>% 
    mutate(area_type = case_when(
      str_detect(area_code, "^S12+") ~ "local authority",
      str_detect(area_code, "^S08+") ~ "health board"))
}

pop_data <- add_area_type_col(pop_data) %>% 
  select(area_code, reference_area, area_type, year, sex, value)

# add total pop for each area, each year
pop_data_all <- pop_data %>%
  group_by(area_code, year) %>% 
  summarise(area_code, reference_area, area_type, year,
            sex = "All", value = sum(value))

pop_data <- pop_data %>% 
  bind_rows(pop_data_all) %>% 
  # remove duplicate rows generated by the sum
  unique()

pop_data %>% 
  write_csv("data/clean_data/population_estimates.csv")


# ----- Healthy Life Expectancy ------

# read in data for male and female HLE from separate files
male_hle_data <- read_csv("data/raw_data/male-healthy-life-expectancy.csv",
                          skip = 10)
female_hle_data <- read_csv("data/raw_data/female-healthy-life-expectancy.csv",
                            skip = 10)

# convert reference periods to long format, apply same pivot to both dfs
pivot_hle_long <- function(hle_df, df_sex) {
  long_df <- hle_df %>% 
    pivot_longer(-c(1,2), names_to = "ref_period",
                 values_to = "value") %>% 
    janitor::clean_names() %>% 
    mutate(area_code = str_extract(
      http_purl_org_linked_data_sdmx_2009_dimension_number_ref_area,
      "S[0-9]+$")) %>% 
    select(-1) %>% 
    # filter for only Health Boards at this time
    filter(!str_detect(area_code, "^S9")) %>% 
    # add sex reference column
    mutate(sex = df_sex)
}

tidy_male_hle <- pivot_hle_long(male_hle_data, "Male")
tidy_female_hle <- pivot_hle_long(female_hle_data, "Female")

# combine dfs
hle_data <- tidy_male_hle %>% 
  bind_rows(tidy_female_hle)

hle_data <- add_area_type_col(hle_data)

# generate standard output column form
hle_data <- hle_data %>% 
  select(area_code,
         reference_area,
         area_type,
         reference_period = ref_period,
         sex,
         value
         )

# write data to clean csv
hle_data %>% 
  write_csv("data/clean_data/healthy_life_expectancy.csv")

# update dataset_lookup
updated_lookup <- update_lookup(URI_name = "healthy-life-expectancy")

# ----- Council House Sales -----

council_house_data <- read_csv("data/raw_data/council_house_sales.csv") %>% 
  janitor::clean_names()

# units = dwellings
council_houses_better_vars <- council_house_data %>% 
  select(-c(measurement, units), area_code = feature_code, year = date_code) %>%
  # retain only health boards (S08) and local authority (S12) codes
  filter(str_detect(area_code, "^S08|^S12")) %>% 
  mutate(year = as.integer(year),
         value = as.integer(value)) %>% 
  left_join(datazone_lookup, by = c("area_code" = "area_code")) %>% 
  select(area_code,
         reference_area = area_name,
         area_type,
         year,
         dwelling_type,
         value)

council_houses_better_vars %>% 
  write_csv("data/clean_data/council_house_sales.csv")

updated_lookup <- update_lookup(URI_name = "council-house-sales")

# ----- Adults with low or no qualifications ----

# data comes from package: opendatascot
# geographic areas can be got only one at a time. get each then bind
adults_with_low_no_qualifications <- ods_dataset(
  "adults-16-64-years-with-low-or-no-qualifications",geography = "la"
  ) %>% 
  bind_rows(ods_dataset("adults-16-64-years-with-low-or-no-qualifications",
                        geography = "hb"))

# join with datazone lookup and clean up format for final view
adults_with_low_no_qualifications_clean <- adults_with_low_no_qualifications %>% 
  janitor::clean_names() %>% 
  mutate_if(is.character, str_to_title) %>%
  mutate(age = factor(age,
                      levels = c("16-64", "16-24", "25-34", "35-49", "50-64"))) %>% 
  rename(area_code = ref_area,
         year = ref_period) %>% 
  left_join(datazone_lookup, by = c("area_code" = "area_code")) %>% 
  select(area_code,
         reference_area = area_name,
         area_type,
         year,
         gender,
         age,
         measure_type,
         value)

# write to fresh csv
adults_with_low_no_qualifications_clean %>% 
  write_csv("data/clean_data/low_no_qualifications.csv")

updated_lookup <- update_lookup(URI_name = "adults-16-64-years-with-low-or-no-qualifications")

# ----- Alcohol related discharges -----

# 1. get data
alcohol_related_discharge_data <- ods_dataset("alcohol-related-discharge",
                                              geography = "la") %>% 
  bind_rows(ods_dataset("alcohol-related-discharge",
                        geography = "hb"))

# 2. clean data
alcohol_related_discharge_data_clean <- alcohol_related_discharge_data %>% 
  janitor::clean_names() %>%
  rename(area_code = ref_area) %>% 
  mutate_if(is.character, str_to_title) %>%
  # Ratios don't seem to make sense - perhaps why dataset is obsolete?
  filter(measure_type != "Ratio") %>% 
  left_join(datazone_lookup, by = c("area_code" = "area_code")) %>% 
  select(area_code,
         reference_area = area_name,
         area_type,
         ref_period,
         value) %>% 
  mutate(value = as.integer(value))

# 3. write data
alcohol_related_discharge_data_clean %>% 
  write_csv("data/clean_data/alcohol_related_discharge.csv")

# 4. update dataset lookup
updated_lookup <- update_lookup(URI_name = "alcohol-related-discharge")



# ----- Alcohol Related Hospital Statistics -----

arhs_data <- read_csv("data/raw_data/alcohol-related-hospital-stats.csv")

arhs_data_clean <- arhs_data %>%
  janitor::clean_names() %>% 
  rename(area_code = feature_code,
         reference_period = date_code) %>% 
  inner_join(datazone_lookup, by = c("area_code" = "area_code")) %>% 
  select(area_code,
         reference_area = area_name,
         area_type,
         reference_period,
         alcohol_condition,
         measure_type = measurement,
         units,
         value)

arhs_data_clean %>% 
  write_csv("data/clean_data/alcohol_related_hospital_stats.csv")

updated_lookup <- update_lookup(
  URI_name = "alcohol-related-hospital-statistics"
  )


# ----- Write Dataset Lookup (must be last) ------

# update dataset lookup csv
updated_lookup %>% 
  write_csv("data/clean_data/ods_dataset_lookup.csv")